const config = {
  AppName: 'AoWallet',
  AppVersion: '0.0.3',
  tokenType: 'AR', // AR or XWE
  tokenName: 'AR',
  backEndApi: 'https://arweave.net',
  backEndApiChatBook: '',
  AoConnectWebSite: "https://www.ao.link",
  AoConnectAoLink: "https://www.ao.link/#",
  AoTokenProcessTxId: "Pi-WmAQp2-mh-oWH9lWpz5EthlUDj_W0IusAv-RXhRk",
  AoConnectModule: 'JdN3ffZQaFE33-s20LSp2uLhm9Z94wnG59aLRnBAecU',
  AoConnectScheduler: 'fcoN_xJeisVsPXA-trzVAuIiqO3ydLQxM-L4XbrQKzY',
  AoConnectMyProcessTxIds: 'w6HQkGKz9VKszy1pT9JcqWUlElv5smxDI_Inv1OOeqc',
  AoConnectChivesServerTxId: 'cC3CM1npsgqmFygx--WUooDj5SQMDEwIBFKiuGuqu5Y',
  AoConnectChivesServerUser: 'B7IT6nWYrkE7JDfSgIM_wiuRylP9W3Tagicl428m1gI',
  AoConnectChivesEmailServerData: 'XfYhx10ueGxMwMWyVKAH2O18LJisSkUQATrga9z9Ggs',
  AoConnectGithub: 'https://github.com/chives-network/AoWallet',
  chivesWallets: 'ChivesWallets',
  chivesCurrentWallet: 'ChivesCurrentWallet',
  chivesWalletNickname: 'ChivesWalletNickname',
  chivesDriveActions: 'ChivesDriveActions',
  chivesTxStatus: 'ChivesTxStatus',
  chivesLanguage: 'ChivesLanguage',
  chivesProfile: 'ChivesProfile',
  chivesReferee: 'ChivesReferee',
  chivesContacts: 'ChivesContacts',
  chivesMyAoTokens: 'ChivesMyAoTokens',
  chivesAllAoTokens: 'ChivesAllAoTokens',
  chivesIsSetPassword: 'ChivesIsSetPassword',
  chivesAllAoFaucets: 'ChivesAllAoFaucets',
  AoConnectChatRoom: 'AoConnectChatRoom',
  EncryptGrade: 'PIN',
  AoConnectBlockTxIds: ['tXnvoxbygi1OIgYzcFC1Qjgrf2Sq9MHgoYBKJkXMV2E']
}

export default config;