// 页面切场动画
const transitionList = [
  {
    name: "分割",
    config: {
      split: {
        dir: "in",
      },
      spd: "slow",
    },
    key: "split",
  },
  {
    name: "切出",
    config: {
      cut: {},
      spd: "fast",
    },
    key: "cut",
  },
  {
    name: "形状",
    config: {
      spd: "slow",
      wedge: true,
    },
    key: "wedge",
  },
  {
    name: "抽出",
    config: {
      pull: {
        dir: "l",
      },
      spd: "med",
    },
    key: "pull",
  },
  {
    name: "推出",
    config: {
      spd: "slow",
      push: {
        dir: "u",
      },
    },
    key: "push",
  },
  {
    name: "插入",
    config: {
      cover: {
        dir: "d",
      },
      spd: "slow",
    },
    key: "cover",
  },
  {
    name: "擦除",
    config: {
      wipe: {
        dir: "l",
      },
      spd: "slow",
    },
    key: "wipe",
  },
  {
    name: "新闻快报",
    config: {
      spd: "med",
      newsflash: true,
    },
    key: "newsflash",
  },
  {
    name: "梳理",
    config: {
      spd: "slow",
      comb: {
        dir: "horz",
      },
    },
    key: "comb",
  },
  {
    name: "棋盘",
    config: {
      spd: "slow",
      checker: {
        dir: "horz",
      },
    },
    key: "checker",
  },
  {
    name: "淡出",
    config: {
      fade: {},
      spd: "med",
    },
    key: "fade",
  },
  {
    name: "溶解",
    config: {
      spd: "slow",
      dissolve: true,
    },
    key: "dissolve",
  },
  {
    name: "百叶窗",
    config: {
      blinds: {
        dir: "horz",
      },
      spd: "slow",
    },
    key: "blinds",
  },
  {
    name: "线条",
    config: {
      spd: "slow",
      randomBar: {
        dir: "vert",
      },
    },
    key: "randomBar",
  },
  {
    name: "轮幅",
    config: {
      spd: "slow",
      wheel: {
        spokes: 8,
      },
    },
    key: "wheel",
  },
  {
    name: "随机",
    config: {
      random: true,
      spd: "slow",
    },
    key: "random",
  },
];

// 元素动画
const animationList = [
  {
    name: "退场动画",
    children: [
      {
        name: "消失",
        children: [
          {
            name: "",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 1,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "飞出",
        children: [
          {
            duration: 500,
            name: "到顶部",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 2,
            presetSubtype: 1,
          },
          {
            duration: 500,
            name: "到右侧",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 2,
            presetSubtype: 2,
          },
          {
            duration: 500,
            name: "到右上部",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 2,
            presetSubtype: 3,
          },
          {
            duration: 500,
            name: "到底部",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 2,
            presetSubtype: 4,
          },
          {
            duration: 500,
            name: "到右下部",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 2,
            presetSubtype: 6,
          },
          {
            duration: 500,
            name: "到左侧",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 2,
            presetSubtype: 8,
          },
          {
            duration: 500,
            name: "到左上部",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 2,
            presetSubtype: 9,
          },
          {
            duration: 500,
            name: "到左下部",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 2,
            presetSubtype: 12,
          },
        ],
      },
      {
        name: "百叶窗",
        children: [
          {
            duration: 500,
            name: "垂直",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 3,
            presetSubtype: 5,
          },
          {
            duration: 500,
            name: "水平",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 3,
            presetSubtype: 10,
          },
        ],
      },
      {
        name: "盒状",
        children: [
          {
            duration: 500,
            name: "内",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 4,
            presetSubtype: 16,
          },
          {
            duration: 500,
            name: "外",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 4,
            presetSubtype: 32,
          },
        ],
      },
      {
        name: "棋盘",
        children: [
          {
            duration: 500,
            name: "上",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 5,
            presetSubtype: 5,
          },
          {
            duration: 500,
            name: "跨越",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 5,
            presetSubtype: 10,
          },
        ],
      },
      {
        name: "圆形扩展",
        children: [
          {
            duration: 998,
            name: "内",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 6,
            presetSubtype: 16,
          },
          {
            duration: 998,
            name: "外",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 6,
            presetSubtype: 32,
          },
        ],
      },
      {
        name: "缓慢移除",
        children: [
          {
            duration: 1000,
            name: "到顶部",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 7,
            presetSubtype: 1,
          },
          {
            duration: 1000,
            name: "到右侧",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 7,
            presetSubtype: 2,
          },
          {
            duration: 1000,
            name: "到底部",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 7,
            presetSubtype: 4,
          },
          {
            duration: 1000,
            name: "到左侧",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 7,
            presetSubtype: 8,
          },
        ],
      },
      {
        name: "菱形",
        children: [
          {
            duration: 1000,
            name: "内",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 8,
            presetSubtype: 16,
          },
          {
            duration: 1000,
            name: "外",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 8,
            presetSubtype: 32,
          },
        ],
      },
      {
        name: "向外溶解",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 9,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "渐变",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 10,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "闪烁一次",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 11,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "切出",
        children: [
          {
            duration: 500,
            name: "到顶部",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 12,
            presetSubtype: 1,
          },
          {
            duration: 500,
            name: "到右侧",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 12,
            presetSubtype: 2,
          },
          {
            duration: 500,
            name: "到底部",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 12,
            presetSubtype: 4,
          },
          {
            duration: 500,
            name: "到左侧",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 12,
            presetSubtype: 8,
          },
        ],
      },
      {
        name: "十字形扩展",
        children: [
          {
            duration: 1000,
            name: "内",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 13,
            presetSubtype: 16,
          },
          {
            duration: 1000,
            name: "外",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 13,
            presetSubtype: 32,
          },
        ],
      },
      {
        name: "随机线条",
        children: [
          {
            duration: 500,
            name: "垂直",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 14,
            presetSubtype: 5,
          },
          {
            duration: 500,
            name: "水平",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 14,
            presetSubtype: 10,
          },
        ],
      },
      {
        name: "螺旋飞出",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 15,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "劈裂",
        children: [
          {
            duration: 500,
            name: "左右向中央收缩",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 16,
            presetSubtype: 21,
          },
          {
            duration: 500,
            name: "上下向中央收缩",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 16,
            presetSubtype: 26,
          },
          {
            duration: 500,
            name: "中央向左右展开",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 16,
            presetSubtype: 37,
          },
          {
            duration: 500,
            name: "中央向上下展开",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 16,
            presetSubtype: 42,
          },
        ],
      },
      {
        name: "层叠",
        children: [
          {
            duration: 500,
            name: "到顶部",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 17,
            presetSubtype: 1,
          },
          {
            duration: 500,
            name: "到右侧",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 17,
            presetSubtype: 2,
          },
          {
            duration: 500,
            name: "到底部",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 17,
            presetSubtype: 4,
          },
          {
            duration: 500,
            name: "到左侧",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 17,
            presetSubtype: 8,
          },
          {
            duration: 500,
            name: "跨越",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 17,
            presetSubtype: 10,
          },
        ],
      },
      {
        name: "阶梯状",
        children: [
          {
            duration: 500,
            name: "右上",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 18,
            presetSubtype: 3,
          },
          {
            duration: 500,
            name: "右下",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 18,
            presetSubtype: 6,
          },
          {
            duration: 500,
            name: "左上",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 18,
            presetSubtype: 9,
          },
          {
            duration: 500,
            name: "左下",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 18,
            presetSubtype: 12,
          },
        ],
      },
      {
        name: "旋转",
        children: [
          {
            duration: 999,
            name: "垂直",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 19,
            presetSubtype: 5,
          },
          {
            duration: 999,
            name: "水平",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 19,
            presetSubtype: 10,
          },
        ],
      },
      {
        name: "扇形展开",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 20,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "轮子",
        children: [
          {
            duration: 1000,
            name: "1轮幅图案",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 21,
            presetSubtype: 1,
          },
          {
            duration: 1000,
            name: "2轮幅图案",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 21,
            presetSubtype: 2,
          },
          {
            duration: 1000,
            name: "3轮幅图案",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 21,
            presetSubtype: 3,
          },
          {
            duration: 1000,
            name: "4轮幅图案",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 21,
            presetSubtype: 4,
          },
          {
            duration: 1000,
            name: "8轮幅图案",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 21,
            presetSubtype: 8,
          },
        ],
      },
      {
        name: "擦除",
        children: [
          {
            duration: 500,
            name: "自顶部",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 22,
            presetSubtype: 1,
          },
          {
            duration: 500,
            name: "自右侧",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 22,
            presetSubtype: 2,
          },
          {
            duration: 500,
            name: "自底部",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 22,
            presetSubtype: 4,
          },
          {
            duration: 500,
            name: "自左侧",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 22,
            presetSubtype: 8,
          },
        ],
      },
      {
        name: "缩放",
        children: [
          {
            duration: 500,
            name: "内",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 23,
            presetSubtype: 16,
          },
          {
            duration: 500,
            name: "放大到屏幕底部",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 23,
            presetSubtype: 20,
          },
          {
            duration: 500,
            name: "外",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 23,
            presetSubtype: 32,
          },
          {
            duration: 500,
            name: "轻微放大",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 23,
            presetSubtype: 272,
          },
          {
            duration: 500,
            name: "轻微缩小",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 23,
            presetSubtype: 288,
          },
          {
            duration: 500,
            name: "缩小到屏幕中心",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 23,
            presetSubtype: 544,
          },
        ],
      },
      {
        name: "随机效果",
        children: [
          {
            duration: 1,
            name: "",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 24,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "飞旋",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 25,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "弹跳",
        children: [
          {
            duration: 90,
            name: "",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 26,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "颜色打字机",
        children: [
          {
            name: "",
            startType: 1,
            presetClass: "exit",
            text: true,
            attr: {
              dur: "50",
            },
            presetId: 27,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "字幕式",
        children: [
          {
            duration: 2000,
            name: "",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 28,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "渐出",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 29,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "浮动",
        children: [
          {
            name: "",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 30,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "光速",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 34,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "玩具风车",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 35,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "挥舞",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "exit",
            text: true,
            presetId: 38,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "线形",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 39,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "展开",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "exit",
            text: true,
            presetId: 40,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "挥鞭式",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "exit",
            text: true,
            presetId: 41,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "中心旋转",
        children: [
          {
            name: "",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 43,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "渐变式回旋",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 45,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "上升",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 47,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "投掷",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 48,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "回旋",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 49,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "伸缩",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 50,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "放大",
        children: [
          {
            name: "",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 51,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "向下曲线",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 52,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "渐变式缩放",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 53,
            presetSubtype: 16,
          },
        ],
      },
      {
        name: "滑翔",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 54,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "收缩",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 55,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "空翻",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "exit",
            text: true,
            presetId: 56,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "折叠",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "exit",
            text: false,
            presetId: 58,
            presetSubtype: 0,
          },
        ],
      },
    ],
  },
  {
    name: "路径动画",
    children: [
      {
        name: "路径",
        children: [
          {
            duration: 2000,
            name: "",
            startType: 1,
            presetClass: "path",
            text: false,
            attr: {
              path: "M 0 0 L 0.25 0 E",
            },
            presetId: 0,
            presetSubtype: 0,
          },
        ],
      },
    ],
  },
  {
    name: "入场动画",
    children: [
      {
        name: "出现",
        children: [
          {
            name: "",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 1,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "飞入",
        children: [
          {
            duration: 1000,
            name: "自顶部",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 2,
            presetSubtype: 1,
          },
          {
            duration: 1000,
            name: "自右侧",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 2,
            presetSubtype: 2,
          },
          {
            duration: 1000,
            name: "自右上部",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 2,
            presetSubtype: 3,
          },
          {
            duration: 1000,
            name: "自底部",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 2,
            presetSubtype: 4,
          },
          {
            duration: 1000,
            name: "自右下部",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 2,
            presetSubtype: 6,
          },
          {
            duration: 1000,
            name: "自左侧",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 2,
            presetSubtype: 8,
          },
          {
            duration: 1000,
            name: "自左上部",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 2,
            presetSubtype: 9,
          },
          {
            duration: 1000,
            name: "自左下部",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 2,
            presetSubtype: 12,
          },
        ],
      },
      {
        name: "百叶窗",
        children: [
          {
            duration: 1000,
            name: "垂直",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 3,
            presetSubtype: 5,
          },
          {
            duration: 1000,
            name: "水平",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 3,
            presetSubtype: 10,
          },
        ],
      },
      {
        name: "盒状",
        children: [
          {
            duration: 1000,
            name: "内",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 4,
            presetSubtype: 16,
          },
          {
            duration: 1000,
            name: "外",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 4,
            presetSubtype: 32,
          },
        ],
      },
      {
        name: "棋盘",
        children: [
          {
            duration: 1000,
            name: "下",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 5,
            presetSubtype: 5,
          },
          {
            duration: 1000,
            name: "跨越",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 5,
            presetSubtype: 10,
          },
        ],
      },
      {
        name: "圆形扩展",
        children: [
          {
            duration: 1000,
            name: "内",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 6,
            presetSubtype: 16,
          },
          {
            duration: 1000,
            name: "外",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 6,
            presetSubtype: 32,
          },
        ],
      },
      {
        name: "缓慢进入",
        children: [
          {
            duration: 2000,
            name: "自顶部",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 7,
            presetSubtype: 1,
          },
          {
            duration: 2000,
            name: "自右侧",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 7,
            presetSubtype: 2,
          },
          {
            duration: 2000,
            name: "自底部",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 7,
            presetSubtype: 4,
          },
          {
            duration: 2000,
            name: "自左侧",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 7,
            presetSubtype: 8,
          },
        ],
      },
      {
        name: "菱形",
        children: [
          {
            duration: 1000,
            name: "内",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 8,
            presetSubtype: 16,
          },
          {
            duration: 1000,
            name: "外",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 8,
            presetSubtype: 32,
          },
        ],
      },
      {
        name: "向内溶解",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 9,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "渐变",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 10,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "闪烁一次",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 11,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "切入",
        children: [
          {
            duration: 500,
            name: "自顶部",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 12,
            presetSubtype: 1,
          },
          {
            duration: 500,
            name: "自右侧",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 12,
            presetSubtype: 2,
          },
          {
            duration: 500,
            name: "自底部",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 12,
            presetSubtype: 4,
          },
          {
            duration: 500,
            name: "自左侧",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 12,
            presetSubtype: 8,
          },
        ],
      },
      {
        name: "十字形扩展",
        children: [
          {
            duration: 1000,
            name: "内",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 13,
            presetSubtype: 16,
          },
          {
            duration: 1000,
            name: "外",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 13,
            presetSubtype: 32,
          },
        ],
      },
      {
        name: "随机线条",
        children: [
          {
            duration: 1000,
            name: "垂直",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 14,
            presetSubtype: 5,
          },
          {
            duration: 1000,
            name: "水平",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 14,
            presetSubtype: 10,
          },
        ],
      },
      {
        name: "螺旋飞入",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 15,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "劈裂",
        children: [
          {
            duration: 500,
            name: "左右向中央收缩",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 16,
            presetSubtype: 21,
          },
          {
            duration: 500,
            name: "上下向中央收缩",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 16,
            presetSubtype: 26,
          },
          {
            duration: 500,
            name: "中央向左右展开",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 16,
            presetSubtype: 37,
          },
          {
            duration: 500,
            name: "中央向上下展开",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 16,
            presetSubtype: 42,
          },
        ],
      },
      {
        name: "伸展",
        children: [
          {
            duration: 500,
            name: "自顶部",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 17,
            presetSubtype: 1,
          },
          {
            duration: 500,
            name: "自右侧",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 17,
            presetSubtype: 2,
          },
          {
            duration: 500,
            name: "自底部",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 17,
            presetSubtype: 4,
          },
          {
            duration: 500,
            name: "自左侧",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 17,
            presetSubtype: 8,
          },
          {
            duration: 500,
            name: "跨越",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 17,
            presetSubtype: 10,
          },
        ],
      },
      {
        name: "阶梯状",
        children: [
          {
            duration: 500,
            name: "右上",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 18,
            presetSubtype: 3,
          },
          {
            duration: 500,
            name: "右下",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 18,
            presetSubtype: 6,
          },
          {
            duration: 500,
            name: "左上",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 18,
            presetSubtype: 9,
          },
          {
            duration: 500,
            name: "左下",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 18,
            presetSubtype: 12,
          },
        ],
      },
      {
        name: "旋转",
        children: [
          {
            duration: 2000,
            name: "垂直",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 19,
            presetSubtype: 5,
          },
          {
            duration: 2000,
            name: "水平",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 19,
            presetSubtype: 10,
          },
        ],
      },
      {
        name: "扇形展开",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 20,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "轮子",
        children: [
          {
            duration: 1000,
            name: "1轮幅图案",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 21,
            presetSubtype: 1,
          },
          {
            duration: 1000,
            name: "2轮幅图案",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 21,
            presetSubtype: 2,
          },
          {
            duration: 1000,
            name: "3轮幅图案",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 21,
            presetSubtype: 3,
          },
          {
            duration: 1000,
            name: "4轮幅图案",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 21,
            presetSubtype: 4,
          },
          {
            duration: 1000,
            name: "8轮幅图案",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 21,
            presetSubtype: 8,
          },
        ],
      },
      {
        name: "擦除",
        children: [
          {
            duration: 500,
            name: "自顶部",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 22,
            presetSubtype: 1,
          },
          {
            duration: 500,
            name: "自右侧",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 22,
            presetSubtype: 2,
          },
          {
            duration: 500,
            name: "自底部",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 22,
            presetSubtype: 4,
          },
          {
            duration: 500,
            name: "自左侧",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 22,
            presetSubtype: 8,
          },
        ],
      },
      {
        name: "缩放",
        children: [
          {
            duration: 500,
            name: "内",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 23,
            presetSubtype: 16,
          },
          {
            duration: 500,
            name: "外",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 23,
            presetSubtype: 32,
          },
          {
            duration: 500,
            name: "从屏幕底部缩小",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 23,
            presetSubtype: 36,
          },
          {
            duration: 500,
            name: "轻微放大",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 23,
            presetSubtype: 272,
          },
          {
            duration: 500,
            name: "轻微缩小",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 23,
            presetSubtype: 288,
          },
          {
            duration: 500,
            name: "从屏幕中心放大",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 23,
            presetSubtype: 528,
          },
        ],
      },
      {
        name: "随机效果",
        children: [
          {
            duration: 1,
            name: "",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 24,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "飞旋",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 25,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "弹跳",
        children: [
          {
            duration: 290,
            name: "",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 26,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "颜色打字机",
        children: [
          {
            name: "",
            startType: 1,
            presetClass: "entr",
            text: true,
            attr: {
              dur: "50",
            },
            presetId: 27,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "字幕式",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 28,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "渐入",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 29,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "浮动",
        children: [
          {
            name: "",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 30,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "旋转式由远及近",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 31,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "光速",
        children: [
          {
            name: "",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 34,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "玩具风车",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 35,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "升起",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 37,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "挥舞",
        children: [
          {
            name: "",
            startType: 1,
            presetClass: "entr",
            text: true,
            presetId: 38,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "线形",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 39,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "展开",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "entr",
            text: true,
            presetId: 40,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "挥鞭式",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "entr",
            text: true,
            presetId: 41,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "上升",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 42,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "中心旋转",
        children: [
          {
            name: "",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 43,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "渐变式回旋",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 45,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "下降",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 47,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "投掷",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 48,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "回旋",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 49,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "压缩",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 50,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "放大",
        children: [
          {
            name: "",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 51,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "曲线向上",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 52,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "渐变式缩放",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 53,
            presetSubtype: 16,
          },
        ],
      },
      {
        name: "滑翔",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 54,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "展开",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 55,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "空翻",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "entr",
            text: true,
            presetId: 56,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "折叠",
        children: [
          {
            duration: 1000,
            name: "",
            startType: 1,
            presetClass: "entr",
            text: false,
            presetId: 58,
            presetSubtype: 0,
          },
        ],
      },
    ],
  },
  {
    name: "强调动画",
    children: [
      {
        name: "更改填充颜色",
        children: [
          {
            duration: 2000,
            name: "",
            startType: 1,
            presetClass: "emph",
            text: false,
            attr: {
              scheme: "accent2",
            },
            presetId: 1,
            presetSubtype: 2,
          },
        ],
      },
      {
        name: "更改字体",
        children: [
          {
            name: "",
            startType: 1,
            presetClass: "emph",
            text: true,
            attr: {
              font: "黑体",
            },
            presetId: 2,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "更改字体颜色",
        children: [
          {
            duration: 2000,
            name: "",
            startType: 1,
            presetClass: "emph",
            text: true,
            attr: {
              scheme: "accent2",
            },
            presetId: 3,
            presetSubtype: 2,
          },
        ],
      },
      {
        name: "更改字号",
        children: [
          {
            duration: 2000,
            name: "",
            startType: 1,
            presetClass: "emph",
            text: true,
            attr: {
              fontSize: "1.5",
            },
            presetId: 4,
            presetSubtype: 2,
          },
        ],
      },
      {
        name: "更改字形",
        children: [
          {
            duration: 2000,
            name: "无",
            startType: 1,
            presetClass: "emph",
            text: true,
            presetId: 5,
            presetSubtype: 0,
          },
          {
            duration: 2000,
            name: "加粗",
            startType: 1,
            presetClass: "emph",
            text: true,
            presetId: 5,
            presetSubtype: 1,
          },
          {
            duration: 2000,
            name: "斜体",
            startType: 1,
            presetClass: "emph",
            text: true,
            presetId: 5,
            presetSubtype: 2,
          },
          {
            duration: 2000,
            name: "加粗斜体",
            startType: 1,
            presetClass: "emph",
            text: true,
            presetId: 5,
            presetSubtype: 3,
          },
          {
            duration: 2000,
            name: "下划线",
            startType: 1,
            presetClass: "emph",
            text: true,
            presetId: 5,
            presetSubtype: 4,
          },
          {
            duration: 2000,
            name: "加粗下划线",
            startType: 1,
            presetClass: "emph",
            text: true,
            presetId: 5,
            presetSubtype: 5,
          },
          {
            duration: 2000,
            name: "斜体下划线",
            startType: 1,
            presetClass: "emph",
            text: true,
            presetId: 5,
            presetSubtype: 6,
          },
          {
            duration: 2000,
            name: "加粗斜体下划线",
            startType: 1,
            presetClass: "emph",
            text: true,
            presetId: 5,
            presetSubtype: 7,
          },
        ],
      },
      {
        name: "放大缩小",
        children: [
          {
            duration: 2000,
            name: "",
            startType: 1,
            presetClass: "emph",
            text: false,
            presetId: 6,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "更改线条颜色",
        children: [
          {
            duration: 2000,
            name: "",
            startType: 1,
            presetClass: "emph",
            text: false,
            attr: {
              scheme: "accent2",
            },
            presetId: 7,
            presetSubtype: 2,
          },
        ],
      },
      {
        name: "陀螺旋",
        children: [
          {
            duration: 2000,
            name: "",
            startType: 1,
            presetClass: "emph",
            text: false,
            presetId: 8,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "透明",
        children: [
          {
            duration: 2000,
            name: "",
            startType: 1,
            presetClass: "emph",
            text: false,
            presetId: 9,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "加粗闪烁",
        children: [
          {
            duration: 2000,
            name: "",
            startType: 1,
            presetClass: "emph",
            text: true,
            presetId: 10,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "爆炸",
        children: [
          {
            name: "",
            startType: 1,
            presetClass: "emph",
            text: false,
            presetId: 14,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "加粗展示",
        children: [
          {
            duration: 2000,
            name: "",
            startType: 1,
            presetClass: "emph",
            text: true,
            presetId: 15,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "着色",
        children: [
          {
            duration: 2000,
            name: "",
            startType: 1,
            presetClass: "emph",
            text: true,
            attr: {
              scheme: "accent2",
            },
            presetId: 16,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "添加下划线",
        children: [
          {
            duration: 2000,
            name: "",
            startType: 1,
            presetClass: "emph",
            text: true,
            presetId: 18,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "混色",
        children: [
          {
            duration: 2000,
            name: "",
            startType: 1,
            presetClass: "emph",
            text: false,
            attr: {
              scheme: "accent2",
            },
            presetId: 19,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "彩色波纹",
        children: [
          {
            duration: 2000,
            name: "",
            startType: 1,
            presetClass: "emph",
            text: true,
            attr: {
              scheme: "accent2",
            },
            presetId: 20,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "补色",
        children: [
          {
            duration: 2000,
            name: "",
            startType: 1,
            presetClass: "emph",
            text: false,
            presetId: 21,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "补色2",
        children: [
          {
            duration: 2000,
            name: "",
            startType: 1,
            presetClass: "emph",
            text: false,
            presetId: 22,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "对比色",
        children: [
          {
            duration: 2000,
            name: "",
            startType: 1,
            presetClass: "emph",
            text: false,
            presetId: 23,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "加深",
        children: [
          {
            duration: 2000,
            name: "",
            startType: 1,
            presetClass: "emph",
            text: false,
            presetId: 24,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "不饱和",
        children: [
          {
            duration: 2000,
            name: "",
            startType: 1,
            presetClass: "emph",
            text: false,
            presetId: 25,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "忽明忽暗",
        children: [
          {
            duration: 2000,
            name: "",
            startType: 1,
            presetClass: "emph",
            text: false,
            presetId: 26,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "闪动",
        children: [
          {
            duration: 2000,
            name: "",
            startType: 1,
            presetClass: "emph",
            text: false,
            presetId: 27,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "颜色延伸",
        children: [
          {
            duration: 2000,
            name: "",
            startType: 1,
            presetClass: "emph",
            text: true,
            attr: {
              scheme: "accent2",
            },
            presetId: 28,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "变淡",
        children: [
          {
            duration: 2000,
            name: "",
            startType: 1,
            presetClass: "emph",
            text: false,
            presetId: 30,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "样式强调",
        children: [
          {
            duration: 2000,
            name: "",
            startType: 1,
            presetClass: "emph",
            text: true,
            attr: {
              scheme: "accent2",
            },
            presetId: 31,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "跷跷板",
        children: [
          {
            name: "",
            startType: 1,
            presetClass: "emph",
            text: false,
            presetId: 32,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "垂直突出显示",
        children: [
          {
            duration: 1500,
            name: "",
            startType: 1,
            presetClass: "emph",
            text: false,
            attr: {
              scheme: "accent2",
            },
            presetId: 33,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "波浪线",
        children: [
          {
            duration: 2000,
            name: "",
            startType: 1,
            presetClass: "emph",
            text: true,
            presetId: 34,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "闪烁",
        children: [
          {
            duration: 2000,
            name: "",
            startType: 1,
            presetClass: "emph",
            text: false,
            presetId: 35,
            presetSubtype: 0,
          },
        ],
      },
      {
        name: "闪现",
        children: [
          {
            duration: 2000,
            name: "",
            startType: 1,
            presetClass: "emph",
            text: true,
            presetId: 36,
            presetSubtype: 0,
          },
        ],
      },
    ],
  },
]

export { transitionList, animationList }
